version: '3.3'
services:
  chatgpt-bot:
    container_name: chatgpt-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    environment:
      - APP_ID=cli_xxx
      - APP_SECRET=xxx
      - APP_ENCRYPT_KEY=xxx
      - APP_VERIFICATION_TOKEN=xxx
      - BOT_NAME=gpt
      - OPENAI_KEY=sk-xxx,sk-xxx,sk-xxx
      - HTTP_PORT=9000
      - HTTPS_PORT=9001
      - USE_HTTPS=false
      - CERT_FILE=cert.pem
      - KEY_FILE=key.pem
      - API_URL=https://api.openai.com
      - HTTP_PROXY
